print("*"*60)
name = input("Prezado usuario digite o seu nome: \n")
print("*"*60)
curso = input("Qual o curso que voce está fazendo: \n")
print("*"*60)
email = input("Digite o seu Email: \n")
print("*"*60)
telefone = input("Digite o seu telefone: \n")
print("*"*60)
idade = int(input("Digite a sua idade: \n"))
print("*"*60)
renda = float(input("Digite a sua renda: \n"))
print("*"*60)
print("*"*20)
print("\n Relatorio de Dados")
print("*"*20)
print(f" Nome: {name}\n Email: {email}\n Telefone: {telefone}\n idade: {idade}\n Renda R$: {renda:.2f}")